# Numpy Introduction

## 📌 Introduction
NumPy (Numerical Python) is the core package for numerical computing in Python.

**It provides:**

Efficient array operations

Tools for linear algebra, statistics, and more

Better performance than native Python lists for numerical tasks

**Why NumPy?**

Speed: NumPy arrays are stored more efficiently and operate faster than Python lists.
Functionality: Offers advanced functions for scientific computing.

In [2]:
# Install and import numpy
# pip install numpy
import numpy as np

## 🔢 Basic Concepts
Arrays vs Lists

**Python List:** Flexible but slow and memory inefficient for numerical operations.

**NumPy Array:** Fixed-size, homogeneous type, faster computation.

In [3]:
py_list = [1, 2, 3]
np_array = np.array([1, 2, 3])

print(type(py_list))
print(type(np_array))  

<class 'list'>
<class 'numpy.ndarray'>


✅ NumPy arrays support vectorized operations, meaning you don’t need loops.

## 🧱 Creating Arrays
From Python Lists

In [4]:
a = np.array([1, 2, 3])

### functions

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.zeros(2)

array([0., 0.])

In [11]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.full((5,6),3*2)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

## ⚙️ Array Operations
#### Element-wise Arithmetic

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0 0 0]
[1 2 3]


In [18]:
c = 2
print(a+c)

[3 4 5]


In [19]:
print(b*c)

[ 8 10 12]


## 🔍 Indexing and Slicing

In [22]:
a = np.array([10, 20, 30, 40])

print(a[0])       
print(a[1:3])     

10
[20 30]


In [23]:
a[0] = 99
a

array([99, 20, 30, 40])

## Attributes

In [31]:
a = np.arange(6)
b = np.array([(np.arange(6)),(np.arange(6))])

print(a)
print(b)

[0 1 2 3 4 5]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [36]:
# shape
print(a.shape)
print(b.shape)

(6,)
(2, 6)


In [41]:
# Size
print(a.size)
print(b.size)

6
12


In [38]:
# length
print(len(a))
print(len(b))

6
2


In [39]:
# dimension
print(a.ndim)
print(b.ndim)

1
2


## 🧰 Useful Functions

In [54]:
a

array([0, 1, 2, 3, 4, 5])

In [48]:
b

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [43]:
print(np.sum(b))

30


In [44]:
print(np.mean(b))

2.5


In [45]:
print(np.max(b))

5


In [46]:
print(np.min(b))

0


In [47]:
print(np.transpose(b))

[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


In [53]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [60]:
d = np.sort(np.array([9,6,5,2,29,1,6,8,4,10,25,68]))
d

array([ 1,  2,  4,  5,  6,  6,  8,  9, 10, 25, 29, 68])

In [65]:
np.concatenate((a,d))

array([ 0,  1,  2,  3,  4,  5,  1,  2,  4,  5,  6,  6,  8,  9, 10, 25, 29,
       68])

In [66]:
b

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [73]:
b.reshape(3,1,4)

array([[[0, 1, 2, 3]],

       [[4, 5, 0, 1]],

       [[2, 3, 4, 5]]])

#### Covert  1D to 2D array

In [77]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [81]:
a[:,np.newaxis].shape

(8, 1)