# Numpy Indexing & Slicing

In [1]:
import numpy as np

In [5]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
b = np.arange(0,11,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
a[0]

np.int64(1)

In [7]:
a[-1]

np.int64(10)

In [11]:
c = b.reshape(3,2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [12]:
c[1]

array([4, 6])

In [13]:
c[c<5]

array([0, 2, 4])

In [14]:
c[1][1]

np.int64(6)

---
# making an array from diff sources

In [16]:
a = np.arange(0,300,7)
a

array([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
        91,  98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175,
       182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266,
       273, 280, 287, 294])

In [17]:
len(a)

43

In [18]:
arr = a[40:]
arr

array([280, 287, 294])

In [23]:
arr1 = a[:3]
arr1

array([ 0,  7, 14])

In [25]:
c = np.vstack((arr,arr1))
c

array([[280, 287, 294],
       [  0,   7,  14]])

In [26]:
d = np.hstack((arr,arr1))
d

array([280, 287, 294,   0,   7,  14])

In [27]:
d.reshape(2,3)

array([[280, 287, 294],
       [  0,   7,  14]])