# Matrix or Matrices

In [2]:
import numpy as np

In [3]:
# create a 2x3 matrix
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b = np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [5]:
# slicing a matrix of 3x2
c = b[0:3,3:5]
c

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [6]:
b.max()

np.int64(98)

In [7]:
c.min()

np.int64(6)

In [8]:
b.sum()

np.int64(2450)

In [9]:
b.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
b.min(axis=1)

array([ 0, 20, 40, 60, 80])

In [11]:
b.max(axis=0)

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [12]:
b.max(axis=1)

array([18, 38, 58, 78, 98])

In [13]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [14]:
m * np.array([20, 22])

array([[  0,  44],
       [ 80, 132],
       [160, 220],
       [240, 308],
       [320, 396]])

In [18]:
dd = np.vstack((m, np.array([42,44])))

In [20]:
np.flip(dd)

array([[44, 42],
       [18, 16],
       [14, 12],
       [10,  8],
       [ 6,  4],
       [ 2,  0]])

# Array Shape Manipulation
Reshape, Flatten, Ravel

In [21]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
a.shape

(3, 2)

In [23]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [25]:
a.ravel() # Same as flatten but returns a view (if possible)

array([1, 2, 3, 4, 5, 6])

# Advanced Indexing and Boolean Logic
### Integer Indexing

In [28]:
a = np.array([[10, 20], [30, 40], [50, 60]])
a[[0, 2], [1, 0]] 

array([20, 50])

### Boolean Masking

In [29]:
a = np.array([1, 2, 3, 4, 5])
mask = a % 2 == 0
a[mask]

array([2, 4])

In [30]:
np.where(a>2.5)

(array([2, 3, 4]),)

In [34]:
np.where(a > 2, a, -1) 

array([-1, -1,  3,  4,  5])

### Broadcasting 
Broadcasting lets NumPy apply operations to arrays of different shapes.

In [38]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a.shape)
print(b.shape)
a

(3, 1)
(3,)


array([[1],
       [2],
       [3]])

In [37]:
print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### Linear Algebra with np.linalg

In [39]:
from numpy.linalg import inv, eig, det

In [40]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [44]:
inv(A) # Inverse of matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [45]:
eig(A) # Eigenvalues and eigenvectors

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [46]:
det(A) # Determinant

np.float64(-2.0000000000000004)

Matrix Multiplication

In [47]:
np.dot(A, A)

array([[ 7, 10],
       [15, 22]])

In [49]:
A @ A           # Cleaner syntax 

array([[ 7, 10],
       [15, 22]])

### Structured Arrays and Record Arrays
Useful for tabular data with multiple types.

In [51]:
data = np.array([
    (1, 'Alice', 9.5),
    (2, 'Bob', 8.1)
], dtype=[('id', 'i4'), ('name', 'U10'), ('score', 'f4')])

data['name']

array(['Alice', 'Bob'], dtype='<U10')

### Vectorization vs Loops
Avoid Python loops when possible!

In [54]:
# slow
a = np.arange(1000000)
b = np.empty_like(a)
for i in range(len(a)):
    b[i] = a[i] * 2
b

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [56]:
# Fast
b = a * 2
b

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

### Random Numbers (np.random)

In [62]:
np.random.seed(0) ; np.random.rand(4)               # For reproducibility

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [63]:
np.random.rand(3, 2) # diff every time if not seed

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152]])

In [66]:
np.random.rand(3, 2)         # Uniform distribution

array([[0.14335329, 0.94466892],
       [0.52184832, 0.41466194],
       [0.26455561, 0.77423369]])

In [67]:
np.random.randn(3, 2)       # Normal distribution

array([[ 2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877]])

In [68]:
np.random.randint(1, 10, (2, 3))  # Random integers

array([[5, 9, 2],
       [2, 8, 4]], dtype=int32)

In [69]:
np.random.choice([1, 2, 3], 5)  # Random sampling

array([3, 3, 3, 1, 3])

### Advanced Functions and Tricks
Aggregations with Axis

In [75]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
np.sum(a, axis=0) #(column-wise)

[[1 2 3]
 [4 5 6]]


array([5, 7, 9])

In [76]:
print(a)
np.sum(a, axis=1)  #(row-wise)

[[1 2 3]
 [4 5 6]]


array([ 6, 15])

#### np.apply_along_axis()

In [78]:
def my_func(x): return x.max() - x.min()
np.apply_along_axis(my_func, axis=1, arr=a)

array([2, 2])

#### np.tile() and np.repeat()

In [79]:
np.tile([1, 2], 3)    

array([1, 2, 1, 2, 1, 2])

In [80]:
np.repeat([1, 2], 3)  

array([1, 1, 1, 2, 2, 2])

### Practical Use Case: Z-Score Normalization

In [83]:
def z_score(x):
    return (x - np.mean(x)) / np.std(x)

data = np.array([100, 110, 90, 95, 105])
z = z_score(data)
z

array([ 0.        ,  1.41421356, -1.41421356, -0.70710678,  0.70710678])