# 100 numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.22.3
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
a.size * a.itemsize

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a = np.zeros(10)
print(a)
a[4] = 1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
print(v)
v = v[::-1]
v

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
# mat = np.array([(np.arange(0,9,3)),(np.arange(0,9,3)),(np.arange(0,9,3))])
# mat
mat = np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
a = np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.randint(0,10,(3,3,3))

array([[[8, 8, 0],
        [5, 1, 9],
        [2, 7, 6]],

       [[0, 6, 0],
        [4, 1, 8],
        [4, 3, 5]],

       [[7, 5, 0],
        [4, 4, 0],
        [7, 2, 5]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
# a = np.random.random((10,10))
# print("Max : ",a.max())
# print("Min : ",a.min())
a = np.random.randint(0,np.random.randint(1, 1000),(10,10))
print("Max : ",a.max())
print("Min : ",a.min())

Max :  343
Min :  0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
np.random.random(30).mean()

0.5309052304154208

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
n, m = 7 , 7 
a = np.zeros((n,m), dtype=int)
a[0,:] = 1
a[:,-1] = 1
a[-1,:] = 1
a[:,-1] = 1

a

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [16]:
a = np.zeros((5,5), dtype=int)

a = np.pad(a,pad_width=1,mode="constant",constant_values=1)
a

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.ones((5,5), dtype=int)

a = np.pad(a,pad_width=1,mode="constant",constant_values=0)
a

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a = np.array([[0,1],[1,0]])
b = np.tile(a,(4,4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.randint(0,np.random.randint(0,100), (5,5))
print(a)
n = (a-a.min()) / (a.max()-a.min())
n

[[61 37 64 62 69]
 [11 50 37 56  1]
 [29 86  1 18 38]
 [19 47 52 68 31]
 [57 11 45 71 13]]


array([[0.70588235, 0.42352941, 0.74117647, 0.71764706, 0.8       ],
       [0.11764706, 0.57647059, 0.42352941, 0.64705882, 0.        ],
       [0.32941176, 1.        , 0.        , 0.2       , 0.43529412],
       [0.21176471, 0.54117647, 0.6       , 0.78823529, 0.35294118],
       [0.65882353, 0.11764706, 0.51764706, 0.82352941, 0.14117647]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
rgba_dtype = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8)
])
color = np.array((255, 0, 0, 255), dtype=rgba_dtype)

print(color)

(255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a = np.random.randint(0,np.random.randint(1,10), (5,3))
b = np.random.randint(0,np.random.randint(1,10), (3,2))
print("A : ",a)
print("B : ",b)
a@b

A :  [[0 2 2]
 [1 3 1]
 [0 2 1]
 [0 0 0]
 [0 3 0]]
B :  [[0 4]
 [2 1]
 [4 2]]


array([[12,  6],
       [10,  9],
       [ 8,  4],
       [ 0,  0],
       [ 6,  3]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
# a = np.arange(101)
a = np.random.randint(2,100,size=101)
a[(a>=3) & (a<=8)] = -1
a

array([13, 85, 99, 39, 14, 19, 64, 49, 32, -1, 24, 63, 83,  9,  2, -1, 30,
       -1, 56, 59, 44, 14, 62, 96, 67, 13, 56, 78, 14, 38, 52, 81, -1, 22,
       40, 75, 56, 92, 74, 65, 83, 36, 78, 92, -1, 77, 52,  2, 90, 24, 98,
       60, 69, 44, 82, 32, 19, 16, 74, 11, 65, 76, 88, 49, 14, 34, 88, 63,
       -1, 57, 82, 40, 10, 95, 74, 76, 29, 73, 61, -1, 76, 37, 32, 82, 10,
       69, 42, 77, 19, 94, 96, 43, 78, 17, -1, 35, 42, 15, -1, 80, 46])

#### 26. What is the output of the following script? (★☆☆)

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.arange(11)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[         1          1          4         27        256       3125
      46656     823543   16777216  387420489 1410065408]
[  0   1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10, +10, 10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-9.12386653  4.86626249  3.71214912  2.69569121 -7.54268717 -5.99999605
  6.67831904  0.33480601  6.82422805  9.3642949 ]
[-10.   5.   4.   3.  -8.  -6.   7.   1.   7.  10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[0 1 2 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:    ", today)
print("Tomorrow: ", tomorrow)

Yesterday: 2025-04-29
Today:     2025-04-30
Tomorrow:  2025-05-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
a = np.ones(5)*1
b = np.ones(5)*2
print(a)
print(b)
print(np.add(a,b,out=b))
print(np.divide(a,2,out=a))
print(np.negative(a,out=a))
print(np.multiply(a,b,out=a))

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3.]
[0.5 0.5 0.5 0.5 0.5]
[-0.5 -0.5 -0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [ ]:
a = np.random.uniform(0,10,10)
print(a)
print("-"*30)
print(np.floor(a).astype(int))
print("-"*30)
print(np.trunc(a).astype(int))
print("-"*30)
print(a.astype(int))
print("-"*30)
print(np.fix(a).astype(int))
print("-"*30)
print(np.ceil(a).astype(int)-1)
print("-"*30)
print((a-a%1).astype(int))

[3.64077993 9.45245934 9.38874612 7.78756917 9.90384593 1.03529283
 7.91849782 4.55388668 2.76688893 0.37900484]
------------------------------
[3 9 9 7 9 1 7 4 2 0]
------------------------------
[3 9 9 7 9 1 7 4 2 0]
------------------------------
[3 9 9 7 9 1 7 4 2 0]
------------------------------
[3 9 9 7 9 1 7 4 2 0]
------------------------------
[3 9 9 7 9 1 7 4 2 0]
------------------------------
[3 9 9 7 9 1 7 4 2 0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
a = np.arange(5).reshape(1,5)
a = np.tile(a,(5,1))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def gen():
    for x in range(10):
        yield x

a = np,fromiter(gen(),dtype=int,count=-1)
print(a)

(<module 'numpy' from 'c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\__init__.py'>, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.linspace(0,1,12,endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [32]:
a = np.random.randint(0,10,10)
print(a)
print("-"*50)
print(np.sort(a))

[1 1 9 6 1 9 2 5 1 8]
--------------------------------------------------
[1 1 1 1 2 5 6 8 9 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [33]:
# pythons Sum()
a.sum()

43

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [43]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)

print(a)
print(b)
print(np.array_equal(a,b))
(a == b).all()


[8 6 8 7 7 8 9 8 1 5]
[8 8 7 5 9 4 9 5 6 8]
False


False

#### 43. Make an array immutable (read-only) (★★☆)

In [46]:
a = np.arange(10)
a.flags.writeable = False
print(a)
b = a
# OR
tuple(b)

[0 1 2 3 4 5 6 7 8 9]


(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [53]:
mat = np.random.randint(0,10,(10,2))
print(mat)
x = mat[:,0]
y = mat[:,1]

r = np.sqrt(x**2 + y**2)
thetha = np.arctan2(y,x)

polar = np.column_stack((r,thetha))
polar

[[1 6]
 [7 8]
 [7 6]
 [0 5]
 [0 6]
 [8 8]
 [0 2]
 [0 4]
 [3 9]
 [7 5]]


array([[ 6.08276253,  1.40564765],
       [10.63014581,  0.85196633],
       [ 9.21954446,  0.70862627],
       [ 5.        ,  1.57079633],
       [ 6.        ,  1.57079633],
       [11.3137085 ,  0.78539816],
       [ 2.        ,  1.57079633],
       [ 4.        ,  1.57079633],
       [ 9.48683298,  1.24904577],
       [ 8.60232527,  0.62024949]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [59]:
a = np.random.rand(10)
print(a)
a[a==a.max()] = 0
a


[0.30804195 0.23692072 0.20088928 0.50901626 0.48622363 0.22443536
 0.31114435 0.57622876 0.54749548 0.50995589]


array([0.30804195, 0.23692072, 0.20088928, 0.50901626, 0.48622363,
       0.22443536, 0.31114435, 0.        , 0.54749548, 0.50995589])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [65]:
a = np.zeros((5,5),[('x',float),('y',float)])

x, y = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

a['x'], a['y'] = x,y
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [67]:
X = np.arange(5)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

-131.91659501325756


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [68]:
# For floating point types
print("Floating Point Types:")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype}: min = {info.min}, max = {info.max}")

# For integer types
print("\nInteger Types:")
for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: min = {info.min}, max = {info.max}")

Floating Point Types:
<class 'numpy.float16'>: min = -65504.0, max = 65504.0
<class 'numpy.float32'>: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38
<class 'numpy.float64'>: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308

Integer Types:
<class 'numpy.int8'>: min = -128, max = 127
<class 'numpy.int16'>: min = -32768, max = 32767
<class 'numpy.int32'>: min = -2147483648, max = 2147483647
<class 'numpy.int64'>: min = -9223372036854775808, max = 9223372036854775807
<class 'numpy.uint8'>: min = 0, max = 255
<class 'numpy.uint16'>: min = 0, max = 65535
<class 'numpy.uint32'>: min = 0, max = 4294967295
<class 'numpy.uint64'>: min = 0, max = 18446744073709551615


#### 49. How to print all the values of an array? (★★☆)

In [75]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [77]:
# Create an array Z of integers from 0 to 99
Z = np.arange(100)

# Generate a random scalar v between 0 and 100
v = np.random.uniform(0, 100)

# Find the index of the closest value in Z to v
index = (np.abs(Z - v)).argmin()

# Print the closest value
print(Z[index])

12


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)