# 100 numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.22.3
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
a.size * a.itemsize

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a = np.zeros(10)
print(a)
a[4] = 1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
print(v)
v = v[::-1]
v

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
# mat = np.array([(np.arange(0,9,3)),(np.arange(0,9,3)),(np.arange(0,9,3))])
# mat
mat = np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
a = np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.randint(0,10,(3,3,3))

array([[[6, 1, 9],
        [8, 4, 9],
        [8, 1, 6]],

       [[4, 7, 0],
        [6, 0, 3],
        [3, 9, 2]],

       [[0, 4, 8],
        [2, 7, 7],
        [4, 5, 7]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
# a = np.random.random((10,10))
# print("Max : ",a.max())
# print("Min : ",a.min())
a = np.random.randint(0,np.random.randint(1, 1000),(10,10))
print("Max : ",a.max())
print("Min : ",a.min())

Max :  387
Min :  2


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
np.random.random(30).mean()

0.4677340153902177

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
n, m = 7 , 7 
a = np.zeros((n,m), dtype=int)
a[0,:] = 1
a[:,-1] = 1
a[-1,:] = 1
a[:,-1] = 1

a

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [16]:
a = np.zeros((5,5), dtype=int)

a = np.pad(a,pad_width=1,mode="constant",constant_values=1)
a

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.ones((5,5), dtype=int)

a = np.pad(a,pad_width=1,mode="constant",constant_values=0)
a

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a = np.array([[0,1],[1,0]])
b = np.tile(a,(4,4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.randint(0,np.random.randint(0,100), (5,5))
print(a)
n = (a-a.min()) / (a.max()-a.min())
n

[[34 56 31 69 21]
 [21 58 16 19  3]
 [ 5 24 60 26 40]
 [69 26  8  9 59]
 [16 13 51 54 20]]


array([[0.46969697, 0.8030303 , 0.42424242, 1.        , 0.27272727],
       [0.27272727, 0.83333333, 0.1969697 , 0.24242424, 0.        ],
       [0.03030303, 0.31818182, 0.86363636, 0.34848485, 0.56060606],
       [1.        , 0.34848485, 0.07575758, 0.09090909, 0.84848485],
       [0.1969697 , 0.15151515, 0.72727273, 0.77272727, 0.25757576]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
rgba_dtype = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8)
])
color = np.array((255, 0, 0, 255), dtype=rgba_dtype)

print(color)

(255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a = np.random.randint(0,np.random.randint(1,10), (5,3))
b = np.random.randint(0,np.random.randint(1,10), (3,2))
print("A : ",a)
print("B : ",b)
a@b

A :  [[1 5 0]
 [0 4 4]
 [5 3 2]
 [0 4 7]
 [0 5 3]]
B :  [[3 6]
 [0 3]
 [5 4]]


array([[ 3, 21],
       [20, 28],
       [25, 47],
       [35, 40],
       [15, 27]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
# a = np.arange(101)
a = np.random.randint(2,100,size=101)
a[(a>=3) & (a<=8)] = -1
a

array([96, 10, 50, 28, 70, 20, 24, 64, 72, 10, 77, 43, 46, 98, 53, 10, 91,
       52, 70, 49, 52, 93, 94, 16, 50, 25, 94,  9, 31, 45, 54, 58, 26, 16,
       30, 30, 82, 91, 37, 68, 43, 12, -1, 42,  9, 13, 10, 43, 65, 69, 38,
       -1, 51, 40, 59, 51, 60, 28, 31, 68, 62, 14, 38, 10, 33, 80, 41, 43,
       -1, 51, 51, 82, 51, 18, 10, 17, 81, 45, 45, 42, -1, 45, 86, -1, 55,
       48, 78, 89, 72, 30, 96, 32, 61, 80, 96, -1, 53, 32, 56, 57, 16])

#### 26. What is the output of the following script? (★☆☆)

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
Z = np.arange(11)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)

[         1          1          4         27        256       3125
      46656     823543   16777216  387420489 1410065408]
[  0   1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [32]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Admin\AppData\Local\Temp\ipykernel_15728\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Admin\AppData\Local\Temp\ipykernel_15728\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [33]:
Z = np.random.uniform(-10, +10, 10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 8.11755425 -0.57234081  6.73205804 -6.87057628 -0.87936385 -8.28922288
  0.04095949 -4.73648522 -3.25114381  9.86941244]
[ 9. -1.  7. -7. -1. -9.  1. -5. -4. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [34]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[0 1 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\Admin\AppData\Local\Temp\ipykernel_15728\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [37]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:    ", today)
print("Tomorrow: ", tomorrow)

Yesterday: 2025-05-07
Today:     2025-05-08
Tomorrow:  2025-05-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [38]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [39]:
a = np.ones(5)*1
b = np.ones(5)*2
print(a)
print(b)
print(np.add(a,b,out=b))
print(np.divide(a,2,out=a))
print(np.negative(a,out=a))
print(np.multiply(a,b,out=a))

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3.]
[0.5 0.5 0.5 0.5 0.5]
[-0.5 -0.5 -0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [40]:
a = np.random.uniform(0,10,10)
print(a)
print("-"*30)
print(np.floor(a).astype(int))
print("-"*30)
print(np.trunc(a).astype(int))
print("-"*30)
print(a.astype(int))
print("-"*30)
print(np.fix(a).astype(int))
print("-"*30)
print(np.ceil(a).astype(int)-1)
print("-"*30)
print((a-a%1).astype(int))

[3.34787553 4.43228928 5.93041662 0.91268543 5.97648008 2.62228029
 4.18443846 6.27451092 6.75300296 8.08756107]
------------------------------
[3 4 5 0 5 2 4 6 6 8]
------------------------------
[3 4 5 0 5 2 4 6 6 8]
------------------------------
[3 4 5 0 5 2 4 6 6 8]
------------------------------
[3 4 5 0 5 2 4 6 6 8]
------------------------------
[3 4 5 0 5 2 4 6 6 8]
------------------------------
[3 4 5 0 5 2 4 6 6 8]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [41]:
a = np.arange(5).reshape(1,5)
a = np.tile(a,(5,1))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [42]:
def gen():
    for x in range(10):
        yield x

a = np,fromiter(gen(),dtype=int,count=-1)
print(a)

(<module 'numpy' from 'c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\__init__.py'>, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [43]:
np.linspace(0,1,12,endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [44]:
a = np.random.randint(0,10,10)
print(a)
print("-"*50)
print(np.sort(a))

[3 6 8 3 1 0 4 7 0 6]
--------------------------------------------------
[0 0 1 3 3 4 6 6 7 8]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [45]:
# pythons Sum()
a.sum()

38

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [46]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)

print(a)
print(b)
print(np.array_equal(a,b))
(a == b).all()


[9 2 6 2 1 9 9 2 9 5]
[4 5 1 0 3 1 0 8 6 5]
False


False

#### 43. Make an array immutable (read-only) (★★☆)

In [47]:
a = np.arange(10)
a.flags.writeable = False
print(a)
b = a
# OR
tuple(b)

[0 1 2 3 4 5 6 7 8 9]


(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [48]:
mat = np.random.randint(0,10,(10,2))
print(mat)
x = mat[:,0]
y = mat[:,1]

r = np.sqrt(x**2 + y**2)
thetha = np.arctan2(y,x)

polar = np.column_stack((r,thetha))
polar

[[3 5]
 [1 2]
 [1 7]
 [7 4]
 [6 3]
 [7 3]
 [9 4]
 [4 1]
 [4 2]
 [1 8]]


array([[5.83095189, 1.03037683],
       [2.23606798, 1.10714872],
       [7.07106781, 1.42889927],
       [8.06225775, 0.51914611],
       [6.70820393, 0.46364761],
       [7.61577311, 0.40489179],
       [9.8488578 , 0.41822433],
       [4.12310563, 0.24497866],
       [4.47213595, 0.46364761],
       [8.06225775, 1.44644133]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [49]:
a = np.random.rand(10)
print(a)
a[a==a.max()] = 0
a


[0.67898619 0.2537805  0.49858649 0.52868938 0.95177619 0.52614962
 0.84362339 0.001558   0.46858835 0.41268523]


array([0.67898619, 0.2537805 , 0.49858649, 0.52868938, 0.        ,
       0.52614962, 0.84362339, 0.001558  , 0.46858835, 0.41268523])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [50]:
a = np.zeros((5,5),[('x',float),('y',float)])

x, y = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

a['x'], a['y'] = x,y
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [51]:
X = np.arange(5)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

-131.91659501325756


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [52]:
# For floating point types
print("Floating Point Types:")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype}: min = {info.min}, max = {info.max}")

# For integer types
print("\nInteger Types:")
for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: min = {info.min}, max = {info.max}")

Floating Point Types:
<class 'numpy.float16'>: min = -65504.0, max = 65504.0
<class 'numpy.float32'>: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38
<class 'numpy.float64'>: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308

Integer Types:
<class 'numpy.int8'>: min = -128, max = 127
<class 'numpy.int16'>: min = -32768, max = 32767
<class 'numpy.int32'>: min = -2147483648, max = 2147483647
<class 'numpy.int64'>: min = -9223372036854775808, max = 9223372036854775807
<class 'numpy.uint8'>: min = 0, max = 255
<class 'numpy.uint16'>: min = 0, max = 65535
<class 'numpy.uint32'>: min = 0, max = 4294967295
<class 'numpy.uint64'>: min = 0, max = 18446744073709551615


#### 49. How to print all the values of an array? (★★☆)

In [53]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [54]:
# Create an array Z of integers from 0 to 99
Z = np.arange(100)

# Generate a random scalar v between 0 and 100
v = np.random.uniform(0, 100)

# Find the index of the closest value in Z to v
index = (np.abs(Z - v)).argmin()

# Print the closest value
print(Z[index])

8


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [55]:
Z = np.zeros(10, [ ('position', [ ('x', float), ('y', float)]),
                   ('color',    [ ('r', float), ('g', float), ('b', float)])])
Z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [56]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.45593952 0.56699518 0.26525051 0.55717564 0.23103401
  0.49451897 0.62181864 0.15216528 0.5332155 ]
 [0.45593952 0.         0.34798704 0.29520599 0.4859586  0.28944753
  0.87972559 0.99535819 0.38732723 0.18752504]
 [0.56699518 0.34798704 0.         0.56332569 0.18014943 0.33758975
  0.8002787  0.88752004 0.42323778 0.17431459]
 [0.26525051 0.29520599 0.56332569 0.         0.63388117 0.28748577
  0.75858389 0.88531893 0.31057148 0.45144212]
 [0.55717564 0.4859586  0.18014943 0.63388117 0.         0.35778577
  0.67217799 0.74415401 0.40513604 0.34050137]
 [0.23103401 0.28944753 0.33758975 0.28748577 0.35778577 0.
  0.59061266 0.70598226 0.10579124 0.3119167 ]
 [0.49451897 0.87972559 0.8002787  0.75858389 0.67217799 0.59061266
  0.         0.12778347 0.49463782 0.86951432]
 [0.62181864 0.99535819 0.88752004 0.88531893 0.74415401 0.70598226
  0.12778347 0.         0.61408917 0.97190645]
 [0.15216528 0.38732723 0.42323778 0.31057148 0.40513604 0.10579124
  0.49463782 0.61408

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [57]:
a = np.arange(10,dtype=np.float32)
print(a)
a = a.astype(np.int32, copy=False)
a

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [58]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11""")

Z = np.genfromtxt(s, delimiter=",", dtype=np.float64, filling_values=0)

print(Z)


[[ 1.  2.  3.  4.  5.]
 [ 6.  0.  0.  7.  8.]
 [ 0.  0.  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [59]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print("*-*"*25)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
*-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-**-*
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [60]:
# Create meshgrid
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))

# Compute Euclidean distance
D = np.sqrt(X**2 + Y**2)

# Gaussian parameters
sigma, mu = 1.0, 0.0

# Apply Gaussian function
G = np.exp(-( (D - mu)**2 / ( 2.0 * sigma**2 ) ))

# Print the result
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [61]:
n=10
a = np.zeros((n,n))
p = 3
np.put(a,np.random.choice(range(n*n),p,replace=False),111111)
a

array([[     0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [     0.,      0.,      0., 111111.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [     0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [     0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [     0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [     0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [     0.,      0.,      0.,      0.,      0.,      0.,      0.,
        111111.,      0.,      0.],
       [     0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [     0.,      0.,      0., 111111.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [     0.,      0.,      0.,   

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [62]:
a = np.random.rand(5, 10)
print(a)
b = a - a.mean(axis=1, keepdims=True)
b

[[0.57081322 0.51202868 0.60482429 0.72713145 0.55796928 0.67151469
  0.75336411 0.20846863 0.69842002 0.38523837]
 [0.28418309 0.5373936  0.57004247 0.86439705 0.86562508 0.43079224
  0.55650291 0.61648443 0.2227399  0.52707226]
 [0.82455109 0.28319845 0.07050251 0.0045543  0.71877129 0.35972591
  0.39466266 0.78153189 0.38779703 0.27984299]
 [0.92080885 0.22183402 0.08656787 0.35448009 0.4811066  0.48540433
  0.25671716 0.97560963 0.22344221 0.84318941]
 [0.14534922 0.13477788 0.43043082 0.3833128  0.83159611 0.77149029
  0.75072628 0.36938546 0.16412635 0.01568214]]


array([[ 1.83594597e-03, -5.69485897e-02,  3.58470164e-02,
         1.58154171e-01, -1.10079916e-02,  1.02537411e-01,
         1.84386835e-01, -3.60508645e-01,  1.29442750e-01,
        -1.83738903e-01],
       [-2.63340213e-01, -1.01297061e-02,  2.25191691e-02,
         3.16873746e-01,  3.18101777e-01, -1.16731062e-01,
         8.97960564e-03,  6.89611270e-02, -3.24783403e-01,
        -2.04510406e-02],
       [ 4.14037275e-01, -1.27315366e-01, -3.40011298e-01,
        -4.05959514e-01,  3.08257476e-01, -5.07878989e-02,
        -1.58511566e-02,  3.71018082e-01, -2.27167775e-02,
        -1.30670822e-01],
       [ 4.35892828e-01, -2.63081997e-01, -3.98348144e-01,
        -1.30435926e-01, -3.80941516e-03,  4.88311715e-04,
        -2.28198855e-01,  4.90693613e-01, -2.61473812e-01,
         3.58273397e-01],
       [-2.54338513e-01, -2.64909855e-01,  3.07430823e-02,
        -1.63749390e-02,  4.31908370e-01,  3.71802555e-01,
         3.51038548e-01, -3.03022715e-02, -2.35561385e-01,
        -3.

#### 59. How to sort an array by the nth column? (★★☆)

In [63]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print("-"*30)
print(Z[Z[:,1].argsort()])


[[9 8 6]
 [2 0 3]
 [6 5 6]]
------------------------------
[[2 0 3]
 [6 5 6]
 [9 8 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [64]:
Z = np.random.randint(0, 3, (3, 10))
print(Z)

result = (~Z.any(axis=0)).any()
print("\nDoes the array have any column that is entirely zero?", result)

[[1 2 0 1 2 1 2 1 2 0]
 [1 1 2 2 2 2 1 0 1 0]
 [2 1 0 0 1 1 0 2 1 1]]

Does the array have any column that is entirely zero? False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [65]:
arr = np.array([10, 30, 45, 60, 75])
target = 50
ans = arr[np.abs(arr - target).argmin()]
ans

45

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [66]:
a = np.random.randint(0,100,(1,3))
b = np.random.randint(0,100,(3,1))
c = np.empty((3, 3), dtype=a.dtype)
print(a)
print(b)
print("*"*50)
print(c)
print("*"*50)
it = np.nditer([a,b,c], flags=['external_loop', 'buffered', 'refs_ok'],
               op_flags=[['readonly'], ['readonly'], ['writeonly']])
for x,y,z in it:
    z[...] = x + y

print("*"*50)
print(c)


[[48 47 38]]
[[49]
 [66]
 [92]]
**************************************************
[[9 8 6]
 [2 0 3]
 [6 5 6]]
**************************************************
**************************************************
[[ 97  96  87]
 [114 113 104]
 [140 139 130]]


#### 63. Create an array class that has a name attribute (★★☆)

In [67]:
class NamedArray(np.ndarray):
    def __new__(self, array, name="no name"):
        obj = np.asarray(array).view(self)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10),"AAA")
print(Z.name)
print (Z)

AAA
[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [68]:
a = np.zeros(10)
b = np.random.randint(0,len(a),20)
print(a)
print(b)
print("*"*50)
np.add.at(a,b,1)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[3 5 3 2 5 4 2 4 1 4 0 1 6 9 0 1 4 3 4 1]
**************************************************
[2. 4. 2. 3. 5. 2. 1. 0. 0. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [69]:
a = [1,2,3,4,5,6]
b = [1,3,9,3,4,1]
c = np.bincount(b,a)
print(c)


[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [70]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [71]:
a = np.random.randint(0,10,(2,2,2,2))
print(a)
sum = a.sum(axis=(-2,-1))
print(sum)

[[[[2 5]
   [8 1]]

  [[6 1]
   [9 7]]]


 [[[1 9]
   [5 3]]

  [[9 7]
   [4 5]]]]
[[16 23]
 [18 25]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [72]:
D = np.array([1, 2, 3, 4, 5, 6])
S = np.array([0, 1, 0, 1, 2, 2])

sums = np.bincount(S, weights=D)

counts = np.bincount(S)

means = sums / counts

print("Means:", means)

Means: [2.  3.  5.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [73]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
print(np.diag(np.dot(A, B)))

# Fast version
print(np.sum(A * B.T, axis=1))

# Faster version
print(np.einsum("ij,ji->i", A, B))

[1.06386618 0.41816623 1.49038668 0.51120229 1.61126581]
[1.06386618 0.41816623 1.49038668 0.51120229 1.61126581]
[1.06386618 0.41816623 1.49038668 0.51120229 1.61126581]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [74]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [75]:
a = np.random.randint(0,10,(5,5,3))
b = np.random.randint(0,10,(5,5))

print(a*b[:,:,None])


[[[ 0  0  0]
  [72 72 32]
  [35 20 35]
  [72 56 72]
  [54 18 18]]

 [[40 40 35]
  [30 40  5]
  [35 10 10]
  [21 27 27]
  [ 8 24  0]]

 [[ 0 12  6]
  [ 5  2  9]
  [24 18  0]
  [ 8  8 40]
  [28  0 21]]

 [[ 7  1  8]
  [ 9 18 36]
  [14 42  7]
  [ 3 12  3]
  [20 10 40]]

 [[ 4  6  0]
  [ 0  0  0]
  [ 4  6 14]
  [81  9 72]
  [18 12  0]]]


#### 72. How to swap two rows of an array? (★★★)

In [76]:
a = np.arange(25).reshape(5,5)
print(a)
a[[0,1]] = a[[1,0]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [77]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 55) ( 2,  7) ( 2, 11) ( 2, 27) ( 2, 54) ( 5, 10) ( 5, 70) ( 7, 54)
 (10, 70) (11, 27) (17, 34) (17, 51) (20, 60) (20, 94) (23, 41) (23, 58)
 (34, 51) (34, 77) (41, 58) (51, 89) (51, 94) (54, 73) (54, 83) (55, 55)
 (60, 94) (73, 83) (77, 77) (89, 94)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [78]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [79]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [80]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([1, 2, 3, 4, 5, 6, 7])

window_size = 3
result = sliding_window_view(Z, window_shape=window_size)

print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [81]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.88577749, -0.55113991, -0.20588591, -0.26110318,  0.57547699,
       -0.49691799,  0.27699672,  0.24432608, -0.25983341, -0.69829693,
       -0.3588064 , -0.71128472,  0.04794326,  0.09496812, -0.76495759,
        0.77885329, -0.26005837, -0.93022894,  0.09030102,  0.63720834,
       -0.18140145, -0.57620923,  0.41706866,  0.36598132,  0.16417884,
        0.90445416, -0.51860717, -0.1505655 ,  0.04843519, -0.8866271 ,
       -0.59235902, -0.01490061,  0.97755639,  0.45319969, -0.00797803,
       -0.60033589, -0.68721465,  0.41534038, -0.7939508 ,  0.84344791,
       -0.75331885,  0.66539873,  0.36247091, -0.02330365, -0.57247287,
        0.58630262,  0.79892264, -0.79014133, -0.99000851, -0.35018157,
        0.03158376, -0.25143307, -0.6576485 ,  0.97184344, -0.47631356,
        0.94045162,  0.00704061,  0.27388213,  0.19258219, -0.79213977,
        0.67148197, -0.4971492 , -0.0494463 , -0.99485528,  0.75334897,
       -0.70541073, -0.65876913,  0.44482571,  0.09097145, -0.12

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [82]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 7.4004972   7.93124474 13.86119381  4.95906578 11.54272412 14.85843403
 15.05662454  6.5857502   5.16011035 12.21157727]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [83]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.32509445  2.18235108  1.47965477  1.63883435  7.93806122  4.39220283
   4.58794734  3.45566015  8.38220375  3.72616903]
 [ 8.92669829 17.74421712 11.2607878   7.52145531  4.23501019  6.93992351
   8.51028949  2.03587468  3.02561376 11.61012017]
 [ 0.22939849  5.06167543  2.69327543  2.74439794  7.89264882  4.70360318
   0.46673883  5.63303546  8.66285925  1.61584153]
 [ 9.76336373 17.69208426 12.19127466  5.98975367  3.01134736  5.6112269
   9.37637227  0.30581712  1.70563617 11.16893747]
 [ 0.60517298  2.01364126  2.64972039  8.32033198 13.25716232 10.17513092
   0.73961721 11.02110222 14.12660618  5.60179316]
 [15.01376914 20.42010634 17.65807199  2.60840893  1.21514954  3.30927225
  14.69588975  4.41854488  0.55323804 12.56227646]
 [11.64667915 17.16687361 14.33549136  1.71014128  0.52843003  1.81454596
  11.3413236   4.40717311  2.06986523  9.62023397]
 [ 6.87353933 12.24511783  9.66323341  0.19547793  3.59704729  0.91686346
   6.59765688  5.01332986  4.83114043  5.02731092]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [84]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 9 0 2 7 8 0 1 8 7]
 [6 6 1 4 9 6 9 7 6 9]
 [2 1 8 5 4 3 1 1 1 7]
 [2 2 3 3 6 9 2 4 0 0]
 [0 7 5 4 8 4 2 1 8 4]
 [3 9 8 3 4 8 4 8 5 9]
 [7 9 9 5 7 1 3 2 0 8]
 [1 8 1 3 6 2 3 0 4 7]
 [5 2 5 8 4 2 7 8 2 7]
 [5 3 7 2 3 6 1 7 4 4]]
[[0 0 0 0 0]
 [0 9 9 0 2]
 [0 6 6 1 4]
 [0 2 1 8 5]
 [0 2 2 3 3]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_15728\1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [85]:
from numpy.lib.stride_tricks import sliding_window_view
z = np.arange(1,15)
z = sliding_window_view(z, window_shape=4)
z

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [86]:
a = np.random.uniform(0,100,(10,10))
rank = np.linalg.matrix_rank(a)
print("Rank of A:", rank)
a

Rank of A: 10


array([[35.59967423,  5.01916019, 45.55062978, 13.06544354, 86.36185686,
        44.18099765, 44.61939143, 46.4093362 , 11.21074811, 58.59298751],
       [45.94882466, 10.4139654 , 55.42660362, 12.33532085, 79.64898921,
        64.5653962 , 74.1568438 , 99.8643164 , 66.06120501, 75.52606943],
       [90.37782399, 31.73916958, 71.7744064 , 74.58272357, 51.42872144,
        56.76495992, 76.55074021, 64.05438117, 46.82000861, 96.25467511],
       [51.66383506, 88.09292402, 77.07743317, 78.20515901, 99.10180974,
        70.76364892, 75.66948729, 67.16144556, 91.41328128, 12.42709816],
       [76.55574472, 47.30189454, 32.69632627, 75.07672625, 92.16190882,
        69.09833289, 79.69049748, 89.63985102, 17.55872899, 50.23853259],
       [36.67583112, 93.73208462, 35.96358127, 76.83700947, 24.87862229,
        42.89791303, 47.98487736, 98.71903716,  2.37690379, 12.58414181],
       [95.4862547 , 96.1811476 ,  1.36467575, 38.66364273, 68.64420917,
        64.16955154, 70.51642323, 52.18626624

#### 83. How to find the most frequent value in an array?

In [87]:
Z = np.random.randint(1,11,50)
print(Z)
print("Frequent")
print(np.bincount(Z).argmax())

[ 1  5  6 10  4  3  2  9  3  8  5  4  7  5  2  2  7  7  7  4  5  1  2  4
  1  6  4  9  3  8  2 10  6 10  1  2  8  3  9  3  3  9  8  9  7  3  6  2
  8 10]
Frequent
2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [88]:
from numpy.lib import stride_tricks
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 2 2]
   [4 1 2]
   [4 1 3]]

  [[2 2 1]
   [1 2 3]
   [1 3 4]]

  [[2 1 2]
   [2 3 0]
   [3 4 4]]

  [[1 2 0]
   [3 0 0]
   [4 4 3]]

  [[2 0 3]
   [0 0 4]
   [4 3 3]]

  [[0 3 3]
   [0 4 1]
   [3 3 3]]

  [[3 3 1]
   [4 1 1]
   [3 3 0]]

  [[3 1 1]
   [1 1 3]
   [3 0 1]]]


 [[[4 1 2]
   [4 1 3]
   [2 4 3]]

  [[1 2 3]
   [1 3 4]
   [4 3 0]]

  [[2 3 0]
   [3 4 4]
   [3 0 4]]

  [[3 0 0]
   [4 4 3]
   [0 4 0]]

  [[0 0 4]
   [4 3 3]
   [4 0 1]]

  [[0 4 1]
   [3 3 3]
   [0 1 0]]

  [[4 1 1]
   [3 3 0]
   [1 0 3]]

  [[1 1 3]
   [3 0 1]
   [0 3 2]]]


 [[[4 1 3]
   [2 4 3]
   [2 2 1]]

  [[1 3 4]
   [4 3 0]
   [2 1 0]]

  [[3 4 4]
   [3 0 4]
   [1 0 4]]

  [[4 4 3]
   [0 4 0]
   [0 4 3]]

  [[4 3 3]
   [4 0 1]
   [4 3 4]]

  [[3 3 3]
   [0 1 0]
   [3 4 3]]

  [[3 3 0]
   [1 0 3]
   [4 3 4]]

  [[3 0 1]
   [0 3 2]
   [3 4 2]]]


 [[[2 4 3]
   [2 2 1]
   [3 0 4]]

  [[4 3 0]
   [2 1 0]
   [0 4 0]]

  [[3 0 4]
   [1 0 4]
   [4 0 3]]

  [[0 4 0]
   [0 4 3]
   [0 3 1]]

  [[4 0 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [89]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6 12  2  3  6]
 [12  2  8 11  8]
 [ 2  8  8 42 10]
 [ 3 11 42  5 10]
 [ 6  8 10 10  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [90]:
p, n = 5, 3
A = np.random.rand(p, n, n)
x = np.random.rand(p, n, 1)
result = np.sum(np.matmul(A, x), axis=0)
result

array([[5.12106063],
       [4.77412824],
       [4.08283408]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [91]:
A = np.ones((16, 16))

blocks = A.reshape(4, 4, 4, 4)
print(blocks)
block_sums = blocks.sum(axis=(1, 3))
block_sums

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [92]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0
  1 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [93]:

Z = np.arange(100)
np.random.shuffle(Z)
n = 5

# Slow
print("Slow:", Z[np.argsort(Z)[-n:]])

# Fast
print("Fast:", Z[np.argpartition(-Z, n)[:n]])

Slow: [95 96 97 98 99]
Fast: [99 98 97 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [94]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [95]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [98]:
x = np.random.rand(10**6) 

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

36.9 ms ± 5.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
8.79 ms ± 283 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
5.57 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [99]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 4 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [100]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 3 0]
 [3 4 1]
 [1 0 2]
 [4 1 2]
 [0 0 4]
 [3 2 0]
 [4 4 0]
 [2 0 1]
 [3 2 0]
 [1 3 4]]
[[3 3 0]
 [3 4 1]
 [1 0 2]
 [4 1 2]
 [0 0 4]
 [3 2 0]
 [4 4 0]
 [2 0 1]
 [3 2 0]
 [1 3 4]]
[[3 3 0]
 [3 4 1]
 [1 0 2]
 [4 1 2]
 [0 0 4]
 [3 2 0]
 [4 4 0]
 [2 0 1]
 [3 2 0]
 [1 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [101]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [102]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [103]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.10624884, 0.22454763, 0.4165785 , 0.35341855, 0.24865981,
        0.35370167, 0.44498052, 0.02549593, 0.42772694, 0.41686543],
       [0.17891675, 0.37812489, 0.70149349, 0.59513589, 0.41872837,
        0.59561264, 0.74932081, 0.04293364, 0.7202668 , 0.70197666],
       [0.18035058, 0.38115518, 0.70711525, 0.5999053 , 0.42208405,
        0.60038587, 0.75532586, 0.04327771, 0.72603901, 0.70760229],
       [0.04027078, 0.08510877, 0.15789293, 0.13395384, 0.09424784,
        0.13406115, 0.16865795, 0.00966355, 0.16211844, 0.15800168],
       [0.16839297, 0.3558838 , 0.66023205, 0.56013033, 0.39409901,
        0.56057904, 0.70524619, 0.0404083 , 0.67790112, 0.6606868 ],
       [0.14771711, 0.31218718, 0.57916651, 0.49135563, 0.34571019,
        0.49174924, 0.61865367, 0.03544684, 0.59466611, 0.57956543],
       [0.15108413, 0.31930308, 0.59236786, 0.50255544, 0.35359021,
        0.50295802, 0.63275507, 0.0362548 , 0.60822075, 0.59277587],
       [0.017317  , 0.03659797, 0.0678961

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [104]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [105]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [106]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17872314  0.26596142]
